@FKala.Api_HostAddress = http://localhost:5258



### Beispiel: Abfrage ohne Cache auf Rohdaten
POST {{FKala.Api_HostAddress}}/api/Query
Accept: application/json
Content-Type: text/plain

Load rSOC: Sofar/measure/batteryInput1/0x608_SOC_Bat1[%] 0001-01-01T00:00:00 9999-12-31T00:00:00 NoCache
Load rSOH: Sofar/measure/batteryInput1/0x609_SOH_Bat1[%] 0001-01-01T00:00:00 9999-12-31T00:00:00 NoCache
Aggr SOC: rSOC Aligned_1Month Avg
Aggr SOH: rSOH Aligned_1Month Avg
Publ "SOC,SOH" Default

### Beispiel: persistenter Cache auf Stundenbasis mit Avg
POST {{FKala.Api_HostAddress}}/api/Query
Accept: application/json
Content-Type: text/plain

Load rSOC: Sofar/measure/batteryInput1/0x608_SOC_Bat1[%] 0001-01-01T00:00:00 9999-12-31T00:00:00 Hourly_Avg
Load rSOH: Sofar/measure/batteryInput1/0x609_SOH_Bat1[%] 0001-01-01T00:00:00 9999-12-31T00:00:00 Hourly_Avg
Aggr SOC: rSOC Aligned_1Month Avg
Aggr SOH: rSOH Aligned_1Month Avg
Publ "SOC, SOH" Default

### Beispiel: persistenter Cache auf Minutenbasis mit Avg
POST {{FKala.Api_HostAddress}}/api/Query
Accept: application/json
Content-Type: text/plain

Load rSOC: Sofar/measure/batteryInput1/0x608_SOC_Bat1[%] 0001-01-01T00:00:00 9999-12-31T00:00:00 Minutely_Avg
Load rSOH: Sofar/measure/batteryInput1/0x609_SOH_Bat1[%] 0001-01-01T00:00:00 9999-12-31T00:00:00 Minutely_Avg
Aggr SOC: rSOC Aligned_1Month Avg
Aggr SOH: rSOH Aligned_1Month Avg
Publ "SOC, SOH" Table


### Beispiel: persistenten Cache auf Minutenbasis mit Avg erzwungen rebuilden (ohne Abfrage/Rückgabe)
POST {{FKala.Api_HostAddress}}/api/Query
Accept: application/json
Content-Type: text/plain

Load rSOC: Sofar/measure/batteryInput1/0x608_SOC_Bat1[%] 0001-01-01T00:00:00 9999-12-31T00:00:00 Minutely_Avg_Rebuild
#Load rSOH: Sofar/measure/batteryInput1/0x609_SOH_Bat1[%] 0001-01-01T00:00:00 9999-12-31T00:00:00 Minutely_Avg_Rebuild

### Beispiel: time-weighted Average

POST {{FKala.Api_HostAddress}}/api/Query
Accept: application/json
Content-Type: text/plain

Load rSOC: Sofar/measure/batteryInput1/0x608_SOC_Bat1[%] 2024-04-01T00:00:00Z 2024-09-01T00:00:00Z Auto(999999999999)_WAvg
Aggr SOCavgh: rSOC 01:26:00 Avg
Aggr SOCwavgh: rSOC 01:26:00 WAvg

Aggr SOCavgM1: rSOC Aligned_1Month Avg
Aggr SOCavgM2: SOCavgh Aligned_1Month Avg

Aggr SOCwavgM1: rSOC Aligned_1Month WAvg
Aggr SOCwavgM2: SOCwavgh Aligned_1Month WAvg

Publ "SOCavgM1,SOCavgM2,SOCwavgM1,SOCwavgM2" Table

### NewestOnly
POST {{FKala.Api_HostAddress}}/api/Query
Accept: application/json
Content-Type: text/plain

Load SOC: Sofar/measure/batteryInput1/0x608_SOC_Bat1[%] NewestOnly
Publ "SOC" Table


### Multiple NewestOnly
POST {{FKala.Api_HostAddress}}/api/Query
Accept: application/json
Content-Type: text/plain

Load Holzofen: Heizung$Holzofen NewestOnly
Load Boiler: Heizung$Boiler NewestOnly
Load Nachlauf_Holzofen_1: Heizung$Nachlauf_Holzofen_1 NewestOnly
Load Nachlauf_Holzofen_2: Heizung$Nachlauf_Holzofen_2 NewestOnly
Load Vorlauf_Boiler: Heizung$Vorlauf_Boiler NewestOnly
Load Rücklauf_Boiler: Heizung$Rücklauf_Boiler NewestOnly
Load Vorlauf_Haus_1: Heizung$Vorlauf_Haus_1 NewestOnly
Load Vorlauf_Haus_2: Heizung$Vorlauf_Haus_2 NewestOnly
Load Rücklauf_Haus: Heizung$Rücklauf_Haus NewestOnly

Load Heizraum: Heizung$Heizraum NewestOnly
Publ "Holzofen,Nachlauf_Holzofen_1,Nachlauf_Holzofen_2,Boiler,Vorlauf_Boiler,Rücklauf_Boiler,Vorlauf_Haus_1,Vorlauf_Haus_2,Rücklauf_Haus,Heizraum" Table



### PV Query
POST {{FKala.Api_HostAddress}}/api/Query
Accept: application/json
Content-Type: text/plain

Load rPV1: Sofar/measure/PVInput1/0x586_Leistung_PV1[kW] 2024-04-01T00:00:00Z 2024-09-01T00:00:00Z Hourly_WAvg
Load rPV2: Sofar/measure/PVInput1/0x589_Leistung_PV2[kW] 2024-04-01T00:00:00Z 2024-09-01T00:00:00Z Hourly_WAvg
Load rNetz: Sofar/measure/OnGridOutput/0x488_ActivePower_PCC_Total[kW] 2024-04-01T00:00:00Z 2024-09-01T00:00:00Z Hourly_WAvg
Load rAkku: Sofar/measure/batteryInput1/0x606_Power_Bat1[kW] 2024-04-01T00:00:00Z 2024-09-01T00:00:00Z Hourly_WAvg
Load rVerbrauch: Sofar/measure/OnGridOutput/0x4AF_ActivePower_Load_Sys[kW] 2024-04-01T00:00:00Z 2024-09-01T00:00:00Z Hourly_WAvg

Aggr aPV1: rPV1 Aligned_1Hour Avg
Aggr aPV2: rPV2 Aligned_1Hour Avg
Aggr aNetz: rNetz Aligned_1Hour Avg 
Aggr aAkku: rAkku Aligned_1Hour Avg
Aggr aVerbrauch: rVerbrauch Aligned_1Hour Avg
Aggr aAkkuladung: rAkku Aligned_1Hour Avg


Expr PV: "aPV1.Value + aPV2.Value"
Expr Netzbezug: "aNetz.Value > 0 ? 0 : -aNetz.Value"
Expr Netzeinspeisung: "aNetz.Value < 0 ? 0 : -aNetz.Value"
Expr Akkuentladung: "aAkku.Value > 0 ? 0 : -aAkku.Value"
Expr Akkuladung: "aAkku.Value < 0 ? 0 : -aAkku.Value"
Expr Verbrauch: "-aVerbrauch.Value"


#Publ "aPV1" Table
Publ "Netzbezug,PV,Netzeinspeisung,Akkuentladung,Akkuladung,Verbrauch" Table

### PV Query 2 
POST {{FKala.Api_HostAddress}}/api/Query
Accept: application/json
Content-Type: text/plain


Load rPV1: Sofar/measure/PVInput1/0x586_Leistung_PV1[kW] 2024-04-01T00:00:00Z 2024-09-01T00:00:00Z Hourly_WAvg
Load rPV2: Sofar/measure/PVInput1/0x589_Leistung_PV2[kW] 2024-04-01T00:00:00Z 2024-09-01T00:00:00Z Hourly_WAvg
Load rNetz: Sofar/measure/OnGridOutput/0x488_ActivePower_PCC_Total[kW] 2024-04-01T00:00:00Z 2024-09-01T00:00:00Z Hourly_WAvg
Load rAkku: Sofar/measure/batteryInput1/0x606_Power_Bat1[kW] 2024-04-01T00:00:00Z 2024-09-01T00:00:00Z Hourly_WAvg
Load rVerbrauch: Sofar/measure/OnGridOutput/0x4AF_ActivePower_Load_Sys[kW] 2024-04-01T00:00:00Z 2024-09-01T00:00:00Z Hourly_WAvg

Aggr aPV1: rPV1 Aligned_1Hour WAvg EmptyWindows
Aggr aPV2: rPV2 Aligned_1Hour WAvg EmptyWindows
Aggr aNetz: rNetz Aligned_1Hour WAvg EmptyWindows
Aggr aAkku: rAkku Aligned_1Hour WAvg EmptyWindows
Aggr aVerbrauch: rVerbrauch Aligned_1Hour WAvg EmptyWindows
Aggr aAkkuladung: rAkku Aligned_1Hour WAvg EmptyWindows


Expr PV: "aPV1.Value + aPV2.Value"
Expr Netzbezug: "aNetz.Value > 0 ? 0 : -aNetz.Value"
Expr Netzeinspeisung: "aNetz.Value < 0 ? 0 : aNetz.Value"
Expr Akkuentladung: "aAkku.Value > 0 ? 0 : -aAkku.Value"
Expr Akkuladung: "aAkku.Value < 0 ? 0 : aAkku.Value"
Expr Verbrauch: "aVerbrauch.Value"

Publ "Netzbezug,PV,Netzeinspeisung,Akkuentladung,Akkuladung,Verbrauch" Table


### PV Query 2 
//POST http://naxds2:20080/api/Query
POST {{FKala.Api_HostAddress}}/api/Query
Accept: application/json
Content-Type: text/plain

Var $FROM "2024-09-15T17:55:45"
Var $TO "2024-09-15T18:08:45
Var $CACHE Auto(20000)_Avg
Var $AGG Avg
Var $INTERVAL 20000

Load rPV1: Sofar/measure/PVInput1/0x586_Leistung_PV1[kW] $FROM $TO $CACHE
Load rPV2: Sofar/measure/PVInput1/0x589_Leistung_PV2[kW] $FROM $TO $CACHE
Load rNetz: Sofar/measure/OnGridOutput/0x488_ActivePower_PCC_Total[kW] $FROM $TO $CACHE
Load rAkku: Sofar/measure/batteryInput1/0x606_Power_Bat1[kW] $FROM $TO $CACHE
Load rVerbrauch: Sofar/measure/OnGridOutput/0x4AF_ActivePower_Load_Sys[kW] $FROM $TO $CACHE

Aggr aPV1: rPV1 $INTERVAL $AGG
Aggr aPV2: rPV2 $INTERVAL $AGG
Aggr aNetz: rNetz $INTERVAL $AGG
Aggr aAkku: rAkku $INTERVAL $AGG
Aggr aVerbrauch: rVerbrauch $INTERVAL $AGG
Aggr aAkkuladung: rAkku $INTERVAL $AGG


Expr PV: "aPV1.Value + aPV2.Value"
Expr Netzbezug: "aNetz.Value > 0 ? 0 : -aNetz.Value"
Expr Netzeinspeisung: "aNetz.Value < 0 ? 0 : -aNetz.Value"
Expr Akkuentladung: "aAkku.Value > 0 ? 0 : -aAkku.Value"
Expr Akkuladung: "aAkku.Value < 0 ? 0 : -aAkku.Value"
Expr Verbrauch: "-aVerbrauch.Value"

Publ "Netzbezug,PV,Netzeinspeisung,Akkuentladung,Akkuladung,Verbrauch" Table



### Timezone for AlignedAggregates
//POST http://naxds2:20080/api/Query
POST {{FKala.Api_HostAddress}}/api/Query
Accept: application/json
Content-Type: text/plain

AlTz "Europe/Berlin"

Var $FROM 2023-12-31T23:00:00Z
Var $TO 2024-01-02T23:00:00Z
Var $CACHE NoCache

Load rKaufHeute: Sofar/measure/power/0x68C_Energie_Kauf_Heute[kWh] $FROM $TO $CACHE
#Load rVerbrauchHeute: Sofar/measure/power/0x688_Load_Consumption_Today[kWh] $FROM $TO $CACHE

Aggr aKaufHeute: rKaufHeute Aligned_1Day Last
#Aggr aVerbrauchHeute: rVerbrauchHeute Aligned_1Day Last

Publ "aKaufHeute" Table