@FKala.Api_HostAddress = http://localhost:5258



### Beispiel: Abfrage ohne Cache auf Rohdaten
POST {{FKala.Api_HostAddress}}/api/Query
Accept: application/json
Content-Type: text/plain

Load rSOC: Sofar/measure/batteryInput1/0x608_SOC_Bat1[%] 0001-01-01T00:00:00 9999-12-31T00:00:00 NoCache
Load rSOH: Sofar/measure/batteryInput1/0x609_SOH_Bat1[%] 0001-01-01T00:00:00 9999-12-31T00:00:00 NoCache
Aggr SOC: rSOC Aligned_1Month Avg
Aggr SOH: rSOH Aligned_1Month Avg
Publ "SOC, SOH" Table

### Beispiel: persistenter Cache auf Stundenbasis mit Avg
POST {{FKala.Api_HostAddress}}/api/Query
Accept: application/json
Content-Type: text/plain

Load rSOC: Sofar/measure/batteryInput1/0x608_SOC_Bat1[%] 0001-01-01T00:00:00 9999-12-31T00:00:00 Hourly_Avg
Load rSOH: Sofar/measure/batteryInput1/0x609_SOH_Bat1[%] 0001-01-01T00:00:00 9999-12-31T00:00:00 Hourly_Avg
Aggr SOC: rSOC Aligned_1Month Avg
Aggr SOH: rSOH Aligned_1Month Avg
Publ "SOC, SOH" Default

### Beispiel: persistenter Cache auf Minutenbasis mit Avg
POST {{FKala.Api_HostAddress}}/api/Query
Accept: application/json
Content-Type: text/plain

Load rSOC: Sofar/measure/batteryInput1/0x608_SOC_Bat1[%] 0001-01-01T00:00:00 9999-12-31T00:00:00 Minutely_Avg
Load rSOH: Sofar/measure/batteryInput1/0x609_SOH_Bat1[%] 0001-01-01T00:00:00 9999-12-31T00:00:00 Minutely_Avg
Aggr SOC: rSOC Aligned_1Month Avg
Aggr SOH: rSOH Aligned_1Month Avg
Publ "SOC, SOH" Table


### Beispiel: persistenten Cache auf Minutenbasis mit Avg erzwungen rebuilden (ohne Abfrage/Rückgabe)
POST {{FKala.Api_HostAddress}}/api/Query
Accept: application/json
Content-Type: text/plain

Load rSOC: Sofar/measure/batteryInput1/0x608_SOC_Bat1[%] 0001-01-01T00:00:00 9999-12-31T00:00:00 Minutely_Avg_Rebuild
#Load rSOH: Sofar/measure/batteryInput1/0x609_SOH_Bat1[%] 0001-01-01T00:00:00 9999-12-31T00:00:00 Minutely_Avg_Rebuild

### Beispiel: time-weighted Average

POST {{FKala.Api_HostAddress}}/api/Query
Accept: application/json
Content-Type: text/plain

Load rSOC: Sofar/measure/batteryInput1/0x608_SOC_Bat1[%] 2024-04-01T00:00:00Z 2024-09-01T00:00:00Z Auto(999999999999)_WAvg
Aggr SOCavgh: rSOC 01:26:00 Avg
Aggr SOCwavgh: rSOC 01:26:00 WAvg

Aggr SOCavgM1: rSOC Aligned_1Month Avg
Aggr SOCavgM2: SOCavgh Aligned_1Month Avg

Aggr SOCwavgM1: rSOC Aligned_1Month WAvg
Aggr SOCwavgM2: SOCwavgh Aligned_1Month WAvg

Publ "SOCavgM1,SOCavgM2,SOCwavgM1,SOCwavgM2" Table

### NewestOnly
POST {{FKala.Api_HostAddress}}/api/Query
Accept: application/json
Content-Type: text/plain

Load SOC: Sofar/measure/batteryInput1/0x608_SOC_Bat1[%] NewestOnly
Publ "SOC" Table


### Multiple NewestOnly
POST {{FKala.Api_HostAddress}}/api/Query
Accept: application/json
Content-Type: text/plain

Load Holzofen: Heizung$Holzofen NewestOnly
Load Boiler: Heizung$Boiler NewestOnly
Load Nachlauf_Holzofen_1: Heizung$Nachlauf_Holzofen_1 NewestOnly
Load Nachlauf_Holzofen_2: Heizung$Nachlauf_Holzofen_2 NewestOnly
Load Vorlauf_Boiler: Heizung$Vorlauf_Boiler NewestOnly
Load Rücklauf_Boiler: Heizung$Rücklauf_Boiler NewestOnly
Load Vorlauf_Haus_1: Heizung$Vorlauf_Haus_1 NewestOnly
Load Vorlauf_Haus_2: Heizung$Vorlauf_Haus_2 NewestOnly
Load Rücklauf_Haus: Heizung$Rücklauf_Haus NewestOnly

Load Heizraum: Heizung$Heizraum NewestOnly
Publ "Holzofen,Nachlauf_Holzofen_1,Nachlauf_Holzofen_2,Boiler,Vorlauf_Boiler,Rücklauf_Boiler,Vorlauf_Haus_1,Vorlauf_Haus_2,Rücklauf_Haus,Heizraum" Table